### ISSUE TITLE
没有显示年、月，没有年月前进后退按钮

### ISSUE THREAD

**Issue by leeqx** [apicloudcom/UICalendar#1]

**Comment by WangJi** [comment]
是的啊，我还以为我设置的不对。
打开日历，居然看不出当前是哪年那月

**Comment by sunzhengcuan** [comment]
本模块只显示日历区域，对前端H5开发者而言最大可能的提高了其可自定义性。开源模块源码的初衷就是可以让原生开发者基于此开发更加符合自己项目需求的模块。
